AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM CloudFormation template"

Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "DavidCFN"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "TypeScripters"

  UserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref IAMGroup
      Users:
        - !Ref IAMUser

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/PowerUserAccess"

  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CustomPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource: "*"
      Roles:
        - !Ref IAMRole
