AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for VPC"

Resources:
  MyVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "172.16.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: "Name"
          Value: "MyVPC"

PublicSubnet1A:
  Type: "AWS::EC2::Subnet"
  Properties:
    VpcId: !Ref MyVPC
    CidrBlock: "172.16.0.0/24"
    AvailabilityZone: !Select [0, !GetAZs ""]
    MapPublicIpOnLaunch: true
    Tags:
      - Key: "Name"
        Value: "PublicSubnet1A"
